[metadata]
name = ellinetircd
version = file:version.txt
description = ElliNetIRCd - an asynchronous IRC server
long_description = file:README.md
long_description_content_type = text/markdown
author = ElliNet13
author_email = ellinetircd@ellinet13.com
url = https://github.com/ElliNet13/ElliNetIRCd
project_urls =
  Wiki = https://github.com/ElliNet13/ElliNetIRCd/wiki
  Issues = https://github.com/ElliNet13/ElliNetIRCd/issues
download_url = https://pypi.org/project/ellinetircd/
license = GPL-3.0-or-later
classifiers =
  Environment :: No Input/Output (Daemon)
  Framework :: AsyncIO
  License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)
  Operating System :: OS Independent
  Programming Language :: Python :: 3 :: Only
  Topic :: Communications :: Chat :: Internet Relay Chat

[options]
packages = find:
include_package_data = True
python_requires = >=3.9
install_requires =
  trio
  lupa
  pyyaml
  argon2-cffi
  cryptography

[options.packages.find]
include =
  ellinetircd
  ellinetircd.*

[options.package_data]
ellinetircd.core_plugins = *.lua
ellinetircd.test_plugins = *.lua, *.test
ellinetircd = templates/*.yaml
ellinetircd.sql = *.sql
