name: Package and Publish

on:
  release:
    types: [published]

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest

    environment: pypi

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Check out release tag
      uses: actions/checkout@v7
      with:
        ref: ${{ github.event.release.tag_name }}

    - name: Check release tag
      run: |
        echo "Release: ${{ github.event.release.name }}"
        echo "Tag: ${{ github.event.release.tag_name }}"

    - name: Set up Python 3.14
      uses: actions/setup-python@v7
      with:
        python-version: 3.14.7

    - name: Setup
      run: |
        pip install --upgrade pip
        pip install --upgrade build wheel setuptools

    - name: Build
      run: python -m build

    - name: Test sdist
      run: |
        mkdir ellinetircd-sdist
        tar -xf dist/*.tar.gz -C ellinetircd-sdist
        cd ellinetircd-sdist/*/
        python -m venv venv-sdist
        venv-sdist/bin/pip install -e .
        venv-sdist/bin/python -m unittest
        cd ../..

    - name: Test wheel
      run: |
        python -m venv venv-wheel
        venv-wheel/bin/pip install dist/*.whl
        venv-wheel/bin/python -m unittest

    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
