name: Lint and Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.14.7", "3.12.3"]

    steps:
    - uses: actions/checkout@v7
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v7
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r requirements.txt
        pip install -e .
    - name: Lint
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test
      run: python -m unittest

    # The following steps test the build and installation of the package, similar to what is done on PyPI
    - name: Build
      run: python -m build

    - name: Test sdist
      run: |
        mkdir ellinetircd-sdist
        tar -xf dist/*.tar.gz -C ellinetircd-sdist
        cd ellinetircd-sdist/*/
        python -m venv venv-sdist
        venv-sdist/bin/pip install -e .
        venv-sdist/bin/python -m unittest
        cd ../..

    - name: Test wheel
      run: |
        python -m venv venv-wheel
        venv-wheel/bin/pip install dist/*.whl
        venv-wheel/bin/python -m unittest